name: Deploy to TEST environment

on:
  pull_request:
    branches: [main, prod]
    types: [closed]

env:
  ENVIRONMENT: test
  OLD_TAG: ${{ github.event.pull_request.head.sha }}
  NEW_TAG: ${{ github.sha }}

jobs:
  retag-image:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:
      - name: Dump
        run: |
          echo "Old tag: ${OLD_TAG}"
          echo "New tag: ${NEW_TAG}"

  deploy-test:
    runs-on: ubuntu-22.04
    if: github.base_ref == 'main'
    needs: [retag-image]
    steps:
      - name: Message in progress
        run: echo '${{ env.ENVIRONMENT }} deployment started...'

      - name: Message success
        if: ${{ success() }}
        run: echo 'Success ✅'

      - name: Message failure
        if: ${{ failure() }}
        run: echo 'Failure ❌'
